config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  #match ':controller(/:action(/:id))(.:format)'
  root 'sessions#home'

  #links
  get 'home' => 'sessions#home'
  get 'profile' => 'sessions#profile'

  #users
  resources :users
  get 'users/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  #files
  get 'files' => 'drive_files#index'
  get '/files/new' => 'drive_files#new'
  post 'files' => 'drive_files#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drive_file.rb
class DriveFile < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :drive_files
	validates :username, presence: true, uniqueness: true
	validates :photo,
    attachment_content_type: { content_type: /\Aimage\/.*\Z/ }

	 has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "50x50#" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    helper_method :current_user

  def current_user 
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
  	redirect_to '/login' unless current_user
  end
end

app/controllers/drive_files_controller.rb
class DriveFilesController < ApplicationController
	before_action :require_user, only: [:index, :new, :create]

def index
  	#@drive_files = DriveFile.where('owner = ? OR user_id = ?', current_user.username, current_user.id)
    @drive_files = DriveFile.where('user_id = ?', current_user.id)
 end

 def new
  @drive_file = DriveFile.new
 end

 def create
  @drive_file = DriveFile.new(drive_file_params)
  @drive_file.user_id = current_user.id
  @drive_file.owner = current_user.username
  if @drive_file.save
  	redirect_to '/files'
  else
   render 'new'
  end
 end

 private
 def drive_file_params
  params.require(:drive_file).permit(:name, :type, :owner)
end	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    helper_method :current_user
  def login
  end
  def home
  end
  def profile
  end
	def create
		@user = User.find_by_username(params[:session][:username])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to '/login'
		end
	end
	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to '/signup'
		end
	end

	def edit
    	@user = User.find(params[:id])
  	end

  	def update
    	@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to '/home'
    else
      render 'edit'
    end
  end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :username, :password, :photo)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drive_files_helper.rb
module DriveFilesHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/drive_files/index.html.erb
<% @drive_files.each do |file| %>
	<div class="well messagebody">
		<h1> <%= file.name %> </h1>
		<p> <%= file.type %> </p>
		<p> Owner: <%= file.owner %> </p>
	</div>
<% end %>
<div class="text-center"><%= link_to "Upload new file", 'files/new', class: "btn btn-warning btn-lg" %></div>

app/views/drive_files/new.html.erb
<div class="page">
	<div class="form">
		<%= form_for @drive_file, url: {action: "create"} do |f| %>
			<%= f.text_field :name, placeholder: "File Name", class: "field" %> <br>
			<%= f.select :type, ['image', 'text', 'music', 'config/database', 'video', 'webpage', 'other' ], class: "field" %> <br>
			<%= f.submit "Upload", class: "btn btn-warning btn-lg" %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaxDrive</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap' %>
    <%= stylesheet_link_tag "style" %>
  </head>

  <body>
  <% if current_user %>
    <header>
   		<p> You are logged in as: <%= image_tag current_user.photo.url(:thumb) %> <%= current_user.first_name %> <%= current_user.last_name %> </p>
      <%= link_to "Log Out", logout_path, class: 'menuitem' %>
      <%= link_to "Profile", '/profile', class: "menuitem" %>
      <%= link_to "Storage", '/files', class: "menuitem" %>
      <%= link_to "Home", '/home', class: "menuitem" %>
    </header>
	<% else %>
    <header>
      <p> You are currently not logged in </p>
      <%= link_to "Sign Up", signup_path, class: 'menuitem' %>
   		<%= link_to "Log In", login_path, class: 'menuitem' %>
    </header>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% @page_title = "MaxDrive | Sign Up" %>
<div class="form">
  <h1>Sign Up</h1>
  <%= form_for(@user) do |f| %>
	<%= f.text_field :first_name, placeholder: "First Name", class: "field" %><br>
	<%= f.text_field :last_name, placeholder: "Last Name", class: "field" %><br>
	<%= f.text_field :username, placeholder: "User Name, from 3 to 20 symbols", class: "field" %><br>
	<%= f.password_field :password, placeholder: "Password, from 6  to 20 symbols", class: "field" %><br>
<% end %>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>